name: room_control
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_statusbarcolor: ^0.2.3
  easy_localization:
  hive: ^1.4.4+1
  path_provider:
  flutter_bloc: ^6.1.3
  equatable:
  get_it:
  dartz: ^0.9.2
  fluttertoast: ^7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en-US.json
    - assets/images/mask.png
    - assets/images/loading_icon.png
    - assets/images/app_icon.png

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SFProDisplay-Regular.ttf
