name: room_control
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_statusbarcolor: ^0.2.3
  easy_localization:
  get_it:
  dartz: ^0.9.2
  fluttertoast: ^7.1.8
  provider:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en-US.json
    - assets/images/mask.png
    - assets/images/app_icon.png
    - assets/images/user.png
    - assets/images/bed.png
    - assets/images/room.png
    - assets/images/kitchen.png
    - assets/images/bathtube.png
    - assets/images/house.png
    - assets/images/balcony.png
    - assets/images/icon_bulb.png
    - assets/images/icon_settings.png
    - assets/images/icon_home.png
    - assets/images/lamp.png

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SFProDisplay-Regular.ttf

    - family: RoomControlIcons
      fonts:
        - asset: assets/icons/RoomControlIcons.ttf
