/// Flutter icons RoomControlIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RoomControlIcons
///      fonts:
///       - asset: fonts/RoomControlIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RoomControlIcons {
  RoomControlIcons._();

  static const _kFontFam = 'RoomControlIcons';
  static const String _kFontPkg = null;

  static const IconData Bulb =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData BulbHigh =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bed =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Desk =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData BulbLow =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Password =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Username =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Email =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Loading =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
